---
- name: Create user
  user:
    name: "{{ ucentrald_user }}"
    shell: /bin/bash

- name: Install requirements
  apt: 
    name: git
    state: present
    update_cache: true

- name: Clone ucentrald git repository
  git:
    repo: "{{ ucentrald_repo }}"
    dest: "{{ ucentrald_dest }}"
    force: true
    update: true

- name: chmod to ucentrald_user
  file:
    path: "{{ ucentrald_dest }}"
    state: directory
    recurse: yes
    owner: "{{ ucentrald_user }}"
    group: "{{ ucentrald_user }}"

- name: Install ucentrald config
  template:
    src: ucentrald.cfg.j2
    dest: "{{ ucentrald_dest }}/ucentrald.cfg"
    owner: "{{ ucentrald_user }}"
    group: "{{ ucentrald_user }}"
  notify:
    - restart ucentrald

- name: Install systemd service
  template:
    src: ucentrald.service.j2
    dest: /etc/systemd/system/ucentrald.service

- name: Start ucentrald service
  systemd:
    daemon_reload: true
    enabled: true
    name: ucentrald
    state: started

- name: Install nginx proxy conf
  template:
    src: nginx.proxy.conf.j2
    dest: /etc/nginx/sites-enabled/ucentrald.conf
  notify:
    - reload nginx
  when: ucentrald_self_signed == false
