all:
  hosts:
  children:
    rttys:
      hosts:
        websocket.usync.org:

    ucentrald:
      hosts:
        websocket.usync.org:

    websocket_balancer:
      hosts:
        websocket.usync.org:
