---
- name: Setup rttys
  hosts: rttys
  become: true
  roles:
    - rttys

- name: Setup ucentrald
  hosts: ucentrald
  become: true
  roles:
    - ucentrald

- name: Setup websocket balancer
  hosts: websocket_balancer
  become: true
  roles:
    - websocket_balancer

