- name: Install nginx
  apt:
    name: nginx-extras
    state: latest
    update_cache: true

- name: install letsencrypt
  apt: name=letsencrypt state=latest

- name: Remove default nginx config
  file: name=/etc/nginx/sites-enabled/default state=absent
  notify:
    - reload nginx

- name: Install system nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --standalone -m {{ letsencrypt_email }} --agree-tos -d {{ websocket_url}}
  args:
    creates: /etc/letsencrypt/live/{{ websocket_url }}

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem


- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --standalone -m {{ letsencrypt_email }} --agree-tos -d {{ websocket_url }} && service nginx reload

- name: Create stream.d folder
  file:
    path: /etc/nginx/stream.d/
    state: directory
    mode: '0755'
